import React from 'react';
//import i18n from 'i18next';
import { withNamespaces } from 'react-i18next';
import "./accent.scss";


const Accent = ({ t }) => {
  // const changeLanguage = (lng) => {
  //   i18n.changeLanguage(lng);
  // };


  return (
    <div className="nodeBG">
      <div className="container BG shadow">
        <p>ODE is an high performance library for simulating rigid body dynamics, it has advanced joint types and integrated collision detection with friction. ODE is useful for simulating vehicles, objects in virtual reality environments and virtual creatures.
        Russell Smith is the original author of ODE.
        New in V1.1.0 :
        Since V1.1.0, ODE is compiled to WebAssembly through emscripten, this adds an asynchronous step, the API add a promise wich is resolved when ODE engine is ready!
        Installation :
        

      Boxstack : Drop primitives & mesh object
      Chain : simulate a chain using 30 rigid body with Ball and Socket anchor joint
      HeightField : Drop primitives & mesh object on HeightMap
      Jeep : simulate a jeep using Hinge-2 joint
      Basket : play basketball using triangleMesh collider
      Three.js :

      Boxstack : Drop random objects
      Documentation :
      A start of API documentation generated by jsdoc can be found HERE. The original manual can be found at http://ode.org/ode-latest-userguide.html
      </p>
      </div>
    </div>
  );
};



export default withNamespaces()(Accent);
